language: node_js

node_js:
  - "8"

branches:
  only:
    - master

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script:
  - ng build --prod

deploy:
   provider: cloudfoundry
   username: 
      secure: "KjVasT1tzDHOUV3X2yO+OhiaQEdQdQcL4560mY0melVlqkloaPoVMuew4Xd+KnCsDVTaHZUIr9ndj1tQ+P5otAsYhz5dl8jVj+44TDCm/X+ixB5otHGuQrnpj8+0V5TmM/QxetHQYQzc8xeJHRAqVVq8rir25ORRivLnFu0tb9xB2BD9yS6wDvt7J9vcvxP6yXZI/iDVtCxVAnwpFDOPQH1XUo8Ul9hMzs1BoNcdzLWr4ayycfJouFeAKIG95o7D+8QChNNvAWFj2+SXnXC6j3a8spINrRQJsr2Ig8YUqykd0rlaCqrXvBzAUW9jml+GJTOtaE8eFrNl9wFvzEUAk8i5HtvIcrHV+jSmJNauGVwkDtRIA8wsf0AokvyaJX49v3YLbH1RYUjPPMrs7hkyMC1gpX7PxG7BJWaihveJtF26i+PhFr4XC20r7pejw3kuBTYbwpFIQSAMFzQrXX1AkP4DcWvF8XhvaiW4G1p69jioOuEz9dqnET4rs5M6vBCPVuB1S6YCkz+V0qTA3mGhoi2PG40KDO9rvmIosKwzB9aOMgGliTAx2mFTeV8wosSpWVN1uEy6mcb5yMPRoPAxbrXD3g5WxDrI8ew2NyG8TTMykmDCqfhglLFCazsr86v2a4wYK/DteWYyh5dXfYMe/UbjSc2bB0Ds7KhAqOlP+uU="
   password: 
      secure: "l24uG7DR4YUQdKSiadD4e06X2+I0/hEOeq/BGm3B5bPZKgnsHdS254POHjimyLzxTYJbWS3I25XWZjurheBciR0Z8tTQWiqwMQP1axOz9N4lXOjFwGWLzw1Z/lFcsTdS4G7GG+AMtauGjcNi0uykO4eudPfD4Pkgk7s/PLw9/bCjAGK/TZvBTMVLIc6VYlYpgCgrAFiNbUugu3xg22Qb55+qRtEIS+EvBmIibBOo24NslORQDxAy+4DLqrX4V4r84mvvo65RIwK8zH5Rb/VoJtq4qKmAGrjTG3zTzIp/abVQxNNAi2M9jAyTUWGrjBGA244kWe+xs+CTPfm68Co5OWeb5tAlHhYudUxQO3bLzg5wqekb5T1xgQq5LZew28x3OXqtni9S65BSrGBxWOM4zZeS8emEh1bG6idGOWVaZE6xTaiLypAVBVMH71S24TyikRTou8xPnGIaKWlUrpT9lxHr+Do50iMA2TKzfwNWOzaHGB7TdxX54CMiOqJu3+aMhoZE4WDqO8OefxLKnn3kYOZ4eR9wPbfWVjrJ4GaU/d+i9la7Ij6SK7n9s/1osKwVQiBohmxnJWlYG7QE7xyK7dk3N9d0PEMbMaPlSI5jAmRcGvqmPJu6Jd31dmRT6Wr2UmK3WilOfOSm4RaNeitBm+QzChwr5ZP85/+KsZ/ZYUI="
   api: https://api.run.pivotal.io
   organization:
      secure: "vKkjNFaVa9DQTyf6zIh4cZNzTu90cZXv5Q4rdjO2EbL0PLMv4KlaoqyT63aZScZoRsrDfThyIA4wplSeilFJEzvx+aM5ntb+WFliexBkUVMFCJxBInzvy5J2xl67IWrhL46Nr2kTxulTCfuwE94tj8m4z5z34JI4vHwSLaB16Htfj4BirA/Cik3LQQl+xPhAieIGDHJuWOdKYF9TeU8d6fKHKgD+j0XT16atoMz6JnMZ+DiWv/AdoNF93Yp4/1YX5coh1QxpH2suOgOb2YMpDiOAQMV9oT6CNE8o/RG4URwX+CAvqzeDd9syBj8TTxh0/kYvVqROKN1FYxthEr23rymXkKgqwMsfDSqm69eCQY+UnSzvPtea2Wy9lZSUFuChPWICr0+gqZIGTlP6HhsfT9nQ95UiMn100wE7zLlBcyXd/yC0DOuFCthDbGA+DrXpwVSCwqzp/OcAnQeQN+8Nomqzs3FwBXqKeCpMUBFlz+gVq/oTOMre/fyH0N3B876Y1Bfrh8wFG7GZ8yXqnFWsvXfNIx+ke9dqfXNO4ko8aokm62659h4IODPQxFZLx4E13LSJAylGIMpJd1zodbTI+/aV/iz8mVrnbiic5vVa8jDWS0ZkyN9DAqNVkU6XaaM7Vvrqy8aGWO5wwO0dRCQJkx8qgYYSIVunGw8jzWIm/CY="
   space: qa

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change