language: node_js

node_js:
  - "8"

branches:
  only:
    - master

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script:
  - ng build --prod

deploy:
   provider: cloudfoundry
   username: 
      secure: "MW2ZAyoGEGfA4XZHQ1KTgTIMa2CH9VuTAvIUtxX8EUkvbQh01D3Jx1jKr5lZJqUc+JqSqZHods9kyV3ROOAbdoIvxJ0rbKtwhfL+2704OXQJ0igdl0+xwECFyn48+POurNkzExGxeVUlk4V0caLUUYJV23XdLPJNTggffBP6sy9AcECeGeE+X2p1JWVBfS2Oloea5DFsxRzshv1kRxG8sxlhVzRfWn9x813sk9wHYGT1IlLRPSESLosb6SsCihDysXxi8bs7/TK2lGhDjjR0jlNWAmvhp8OtV6mL5syAuHyzzz51ZrUBSMeAYjZq8YF3gwSyLcs0LW28aLU0M1FMn/aFdpxRPcuE3LX9zGEm9S1qcTP+tVfLLs+jdNn57DbRwRSMvZc/g699aB5QHjbyYgcRCrresp/kXp9tSqNESZU9ksrAkohZ90URCGkpL4ZjsAWEhjylZZkwqTA+HBof5i8JRt0MH6wsO/zXrhTKQeAnna+W4/C71EZN450gEGIGEOMlMhzD06mb5maf4clD8kZ/7ZsxzT60oYgJ0Apg7wt+8rsaQFvAB0MgAY0xMFY+RgTRLXI0ahYKlafyp0xvpxv3pRkgChxz3KNY9jk5EFVWgYM3f8gjjmQu35YCqAjQoLQwBwVI5kz7fv7snX75dS2Tmx7D2F3VA0t+pTa6FJk="
   password: 
      secure: "bHpQKM5HX+Tkxlb531UoRg39ywHX4hBqC1j9dKe3gaQwTcasVR9oor0X9S8BPhBK09LDcGuxudivlNMBKaGk4svK34jjb+XZvhEuIUa7WPC7+6ouYsfmvLO07zWRySaqJVFY+Jf9apP6ozfWxOgye+ofaD/p4haFvnTyEvrXLl17YfYl5iUr98QCctJiiDtifL3ILkxYC6/X7EemGPks2EKEdS978CH5xoSNDqzMIHSq93+r9vcyrJ+AvGlmtsasCYe06+tYZlC45VV8EUoCswn4UjiDrrH2sFj+IYAnYcWcI0GOr1EeCjStQoIkbDQGVGOSiFbggqKbXbydF//S0jJeUhvoE4desPhuXIrue0ZyTe/aSjUpw5vI4859buzBauPBXD9HjvMbzrkTGf55pbUCeJQiL1Exo4o0623FuUOBLMMEqNMQBWntiPWAPLlirQS/bSjqrM+EztpGcBLvvt7+SsmA91asaka/0ChwiagDYOfBssJCoXr+a3WrLa6iG4dgEtajBQmhphbRDzEuDGdnWrSYTeaiCCi27Xi1y1kxZ26YO2GTwP+AjDlX6gu06RVwKYSb22IxkGJ42jSEspIv+I/tXKc4XSOTnL9/snugTMpfjsjZS4tANEeZLRhZhDarVTDJOOnoF/CLoum+9/fsCX1Ujz9I1Y67QiGf1yc="
   api: https://api.run.pivotal.io
   organization:
      secure: "WCOdCPu9Hzq72j2hOsyigTKLohMXiqgZHmL2dGo+SouinDLtgXcoEm6NClOcBue99h93TF9xPE7bR9xgDJYvXfnVc+fxMBbfB02TQmHQ+DsT9y0P0lMsV0AeI8l+NH7tzpl/iG+nJnF8f7T9S1p/h5iGs7OLjohJWZURJYUsn+CwebzSh4Te0CWFXaMl6He6j+6hddNKN9VmHOzAy5sGMPGXIEQMBiWCeFMKXxWPdt5zBGf/xDnCUzV9HouGNReuRL14Jiua0kMLEO3Bme9NaTbSxFprxe85xmT2I0bxnBCFFhTpQ5jhLI/eEMhrS63rMENLvHZqOlG2aXIMg5d9zHV9k+x67J+OxSnMH+5aXTIN5zJbY5HYBweso63IVFswbHQuJnzEBNQnv2TJ+kn6/dZ9/vvtuUh+bgY0IK8aF9Kp8X/Cka+/LHPi8rUpPd9LdFqx1/QY4BrVNeNG/buPOEYBHuhgCEcEa04FXGbKKp1FAovIU3W6IlmgbJGSxcf9at2KEf7oRO3uz+LsNMX4CAFXRZrTKEjMiOqjRlbYYtNdMwko9FpiB1G0f8G8HU3bs+1aAFIQb1STXV2BuPMaj0kaOqk82QcK96GDR8ecgrca4oUDqYnEzos2/t6qe5v1NIBnjKJyGuRifjwPRQoHP9V+tTjeCDvx6gZ142Abno8="
   space: qa

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change