language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script: 
- ng build --prod
deploy:
  provider: cloudfoundry
  username: 
    secure: "yKX2dhFi+W55f6wuJm2SZM0/0tB1rdbe3IVAYkl+4l//B7YiwuNv5Oxk+t/PEo2J0p5AhA0oQwEstRxf8NFZhw8bSRJjKEXs6NFP3ZOSTF/bwhbsJGxJWmDM8LEWMbR+7Vy42N7ySSRYIPeZ/WWPNZGoNBsfGQf4m05gO8dNcCJzl+RcXw14R6tqi99eZO2E+bte1qNN2zMVWpq8AwFlb9ukPji5gZZKnwjn3rXM+1F4h4Kq9OVM/aXE+j8i3fXcOMzLA8r84ML8suD8Q75PbN1I4fAXk9yEIiPvBRJQkq15aipUoPC3MEZqOG9Al7dMIdewCkwK5b7pDGsprqiXLAqXxYi78JuK7TXGINp1mwgCk0o2JVCXvmNx3H9FhBsRxB4VPoXsS3+C39C78qaxJPsCtWg0DHSd/f4vpce2qpqTkgg3Z/1M5tZCBO6mRhkaTpS+ACBEHiI/llB/aZtFiJMIMmB8P2EQESw6LFOOumXEByu9QDL6D/dFbIrqjZDdT2ftUUWEnlVXbmCjj+87y64Y+RAH1WhAygYNYFO2M0kwY7VHlqyOuPN9mw71pgfkqg8m3tFsA66dVxDkrncCMPjo6BQ85C4cVHapBeWHjquebbUTVSr/cXdMXDMQ0NAJSfx3VFKkyjxM6P9aYHiQWoRZuzmT4bTFoPwhoV67rsU="
  password: 
    secure: "Do8ryTKAwXbyOeAD9zEbhmqCwgwu5Fpbpio7FDyv4952XrIPnL6KkgGbrAHGSy4STwOpHA+64j/fPP+vWkMgZt5qlHGdKIybFyXjmtZc+HGbVyn/J+aA9z1serLcS2WQhOK4FW2ZNVgRngKpd/SUnQ/GavtkITCFmbgU+3TqdRWNvsxEncM3JGvLoavrzySAALEQ4mi2Zh8wwfbpMDy6a9u4RiZ+tlxCTFhuKGmwFlypB4c+Y6vZYgNgJxrMrmjp7LBvfWYyijsx1X3+VG+g1U5dAWrjvgrtlxaQR3o5zI4Vnow8AZWyPfher4qQm/jkLbbiV2sMQWzaPMnGkCtxbxDQBU3dIp1bRgevZWBZCvkhg+aHRBQIdY4MlRzdoV70IWd6g60P7AjN3IWJu7XyVW0GBx7nqin24f94zSsZHKt7i5A3sURruTypAH5RSsIB4LY5h6jIoewnecPMAfBwkus+MDVAF0IFEQL09XBvqTVLZjJVKKfyvQjhF7V+CupZqDsvTlZArQ6MzSXvNf8dxNqbBcWEg18LTW8Sc6nRDHYDNHwVMIe5NL+l4e8LnjfDtSMoi3pZ9Cb0TJ7ZDU/8VTqG2d491kYzuZGAzrX2I8ZeaLwHnZyiBdxCMaVbTlQwLXDbNOKLNjckdPQf/m49EbZX1Uj/gDtNq3gmnqUBmck="
  api: https://api.run.pivotal.io
  organization: 
    
  space: qa
notifications:
  email:
    on_failure: change
    on_success: change
