language: node_js

node_js:
  - "8"

branches:
  only:
    - master

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script:
  - ng build --prod

deploy:
   provider: cloudfoundry
   username: 
      secure: "mXE1UuUm9SscAyVGqaq8n4LisTOZJ/HoWNXtf4moKNF4gCgj462QZDV/hiaIcg31gATjCbFOM1YuZuY5NwVcSB115mvct+580uUNzyuH9dqROhoXGzEtKSnp/9qgsmTxMBScE9ik1YDyHuA1VkbucvTi9ckiqWL+OnEQRipHbqOroW3EL63m2+U8QXlCJIAnz1O0ugEeAjAMQRPN3NEuMLHOCwnIpXnDxMzdU/IsSjBcBKj9vsmkM5clawaIQryR9i0xV3XFtrrg+Qw7X2WOQlGCuQy+J6Gf/qZR/3xrsZ9l1lNj0uHsQ6Ha9lzM9Yqlg+1FNuRjjXLI0VM2vMrEg8KFWzHIy+SqdEyhrArEY9W6XDrVRcypDvVFXrbjZq8aiS+dOGh0plGAVtOEbBG/BpB3iQsDeDs7Fmq7mY9EP1aXtw/X91aTYBuP1AQVOE0gBpT1wy5QqJiASxVVul3D1jnygGcPEoC2UOE8X4WLzJF1yjSSp0UukBYeKKLE8l+JFHmDryfT3NqiyVP08TPcCFR09mmfqO1Oqh1yS6gqpLCkIUKlsnVN9fgqt1AnipFzNPa5Lz/wXoE8gAtYadf81+g+2Kkif9ce2cIBJKfcvRHgbLp9HQ8GIITl4qSc7siZsJ4+C8PecM/bkqhVSFUMNgWP+93AUn12suPG8+ZidiU="
   password: 
      secure: SeXgk4uo2t8y32Lns+gMSc97q9f8nTupBIs3PbZd/fmTAQ1EfNfIAdILmrUYrklkPcZ8NkcxeVpIVGXaJaLuNMPWuc3ry3nPX4FLdBLyvuswrOjx88LlWt9/okzRqA7lsxXiLA73Iy7QBkObCzyVqEuVfZrmDZAYE3ftABHLGPMa2/BSD0y6hWOLI4kWLuj1JXhjb48R4HolKAux6rr/n1NvSs/bU3ktWWQaQ2wnkF8nv8ys8tzcevwSVAe/JlbuJemWcL2pwRHyN0h3HTkGMUQ7WdQYYmCNcjsbT/rTp5Ws7efQx5p1grFYBPcOaTY9TpXOpwVlAT661d3FfrkQwnyw4xxu4TvRkWPAKvW7cHvlYG0C1DmVSEb+E+B0+yxKOL0cmWVK61Yz3sspahjU9cZEunmOu1OJtFKuCbXz+uORBsSXi2VBjP7JSqU6prIPv76bM005q5tnz9HhUniryatEHvYF+M1amJsl49bVshAeEpesBDE+k5FuYzOpZjcwTRa1APdlCfhXWv057sfWgNevYFtYKWuypyr653OXNZIaaKFOs1ky7t3s8uKq6rXXC12ngiyThOzj9j1CxaOOm3JQoz/zGC7sSzzRihSZvd6kdoOXiHftIYPfAnS/OI8BKAC8TY1PY9lT6UL0jghNWVclqBQOE9IxDPM5XBITnjE=
   api: https://api.run.pivotal.io
   organization:
      secure: "V1mLnP8Jfo3p1csz/ycr63TLyV0cmUr02cAcnGM/nA6MH74i3RRY6Sc5bkRen+U4By0eWnre1h2IYPlG8hPFbRtwD2HZABdQw6gw6sZWzDD4dVKELHoEWwwNacfMf3H1wfVo2dbSpLCC5CQUsPyxteDG07KVelEYz1gt3T50v+WxPmnXOoI6fFI1dgHnANJMkA7hEJ43TbV2Zpw6K7auUalAvxoTt+EcLWLzc95J6oTBdWmUuu/r3YG3Rgys/8NRRs1aIYw3bucSSwt5+B1qR0pC5rD2jxOy3e1H2Edz72ok60yY+T+YDuNt3xLc7tR48FaXoa8wG4hDdCDoQu4QHFd4imr/rzyKlHG7Mz5KcMbg8HDnAXUbvnn4g3H8nfanMfU96knQjgkOgDaheqaM8Jc0jjfLkhA9ui+aoQFMwBWf3BDTSQAu2B2ei0dXbi44IIIGfDlrTpkRPo8ng8Rx6+xvmJSo8H00UhMDqNOGLDxMe/ndo8Gg1ArUNZR8e/b/IaAIptlkNKoXTt1NkU6ENYPsH9/QtC5qGaKUnti2Cg1Jew7LT3dAjFrzzqr/jAOeu121Qgbwq1AyBE4/rBr9HsJ+0+CIQUt8wuWzVMEfPWBvvZkooto4lZhEIBRK9x8UdytFuxmUCkGem367KKCJ0qg0hgVIv+KnGakIBXlrln0="
   space: qa

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change