language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script: 
- ng build --prod
deploy:
  provider: cloudfoundry
  username: jhonatantiradotiradodeep@gmail.com
  password: 
   secure: "xEKE3I1u16v3kor66opwQ+rfSxcFdwBblEG1EiweF0K23ufYRR/IWQPHkrfX/tFEUxvIJNXSF3jJbVq38Izv41XSkGjJUKEJJbloyPuPeU9CY
3fWEi3n20zkCH84bvSLpOMh/puvIzT/MI6lg2rYwlx4/qTEwKwdZvrIyoQxV1I98hxhdlesrvOTFkrTvgSI4UNTMPZjVcJBOVdyF8b79DWIEiwMIAe2LDTy0
vhAo4Tz7/YUDK0VOrkxnXO0hK+cd4b08PuCqjB6A9kae4J5JbvlglErXMkQM4ZkM23vgFRieQ2GY5ihaov3UoHDJ41oWdkWfrHmb5VdtQscnZc3bxGoM7V7C
aA7PGaG/7kBeCRME7EGvk9BbKvw524agsLSJqY6SPGbpRH6vigptUm0XAMbSn2QY9FM15UrM9z007NCYaJoh3MG+1DYvdT/5bj5A6aDHRqm8B615hpkYrz25
9Nj3B8EnyLTODhcTe/8+GIVnskRmhcrw/n1hymQee0KduO2pnlewj4iWhDX+XmuFlCwnmXK2orVvar1H50CAKlsA6tYxkzviUqQZhYzUR5mc5zCjXPE540BF
qS4wnJB6oydLauO0aoi9grFAtMxT/0DZfZkS02p1c8dkfb68/3mLo+pakt1mAf2y6mjLcpCtEUzEpsuI0/WF1q98cchs+0="
  api: https://api.run.pivotal.io
  organization: kipubit
  space: development
notifications:
  email:
    on_failure: change
    on_success: change