language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script:
- ng build --prod
deploy:
  provider: cloudfoundry
  username:
    secure: hcGXCK7bwhjSYJX+e/rd0TBZvGejTcKIp0pp/2pN0uUxl+INfWwbbWi43Aa0gaiCQTflDJm4lX5FbzSgbJbBLf8SE2Ga6fNxIfkXzxVipNBDw0laLd2sLBPnRsytjaUvovKTfJgfxkJ372kDJc34r2LmwbckY+iuYbw+kFROn3UCRQVUYNVLBjwp7WJDiVjTl/fEgnVQ6gbXeK+uIMEPpHunRiGIqVxKmbcxDhCshuhTHCoW6oM8EKFuUZvdJr87nUmjo3Bsvy6YG+21Yxb4hdkmxiJxROXJzcUtgkzcMDuJBi3k46Fm5P2HB3+aOd9y4xOb+GHlOHpBmog7sJyrVKQ+RNAeZ9346POGTnRzRU1xwEK/DJ0dvt84R6d592k/4MQOxb/pNl7VoLhMapBbT68BbQ/ErqbTAHcpbtUOm5QKCemltxLtUxP/ay3Ar2YVt6vZNafGI+E0JzOCs3vyjp6HYHF73AfNHfQOyPOX5cACzb8JM1qjJol0GMaodfi8Z7gcuHLQo0s0wmalog3s7uisJucGBCPhG0xzcjL/dc5lhhwRKRK4ulWn5G2HxOXJYioF+dQ1uBdieVdQ5DCz+FkkEsZPG3znhbV8hETY1CO6Zps4CCKCGOXbLEdUzhriFSdDMpqUgAw9BuesFShk9XqRzw1h4AfATClVO8daGvU=
  password: 
    secure: J63dnipjTOZ6Kmut7fVKWbrU8cC+ZfJhkts90YVDihMjMeLwtWOVo16fz9t7sCMOTu/WQllZ9Fdfm6up4lwFQM+IegMJWHWwqfoXTdDItgoRoGMqnL0AJtnttscO+6vtilgwtpBlvLwso8ko9kEKsnf8PKmLa6L6fhhz6uzmCJncLRPXN26pOFCrQPUSa3h7qAeuxrmfk0K8oh9334cKPXaT7ffsuDJTB1D2rXhpVVvMxEcpjP/u7qY4pmL+hqwA0nCyFTIl67IfgjKRLnI8itzaBZ4LAso8N6tLv2YQKeeUVFNxjdIurdxn/HA5x+KJ5qpccSm2RWM+BEv9h5l0G9AERrLx4G1XGcHBhf91JwiMISm8zouZrGcvVdZ+/wSPHciRAQEsTURU9wEPb2SML0BKuS8GqnGney/pNSc8XZIvddk5rN/trVy9Q6bFd9LlYMs0MTCc31LM2ccGjNVDTbgTRWZO3JnjI0WyC29RBUoUDoI5ndzHyYtqy9WOxR5HaOIDx/7elWyPV1HcKY19c0wdaJsJgJZwPDRivr8aPBKHZf2/L61hgL0g/FctOW/MIyU8zsB3izwAqS8ICSa3FRgTYEgItxdTs0BTI2fYe51L5NDzHt8iS+E8fyXtBbM2GIaFa6FDOgOR3Ro5AhL5uk4ItlQWIG9SZpeLHjIMiH4=
  api: https://api.run.pivotal.io
  organization: 
    secure: 01+bhLQ/cXN+wOG8B9tPoWpscZuR2q46Uj0EsuqsbDR0F0RmOFKY+k+fL761UxWudVPsyIku8lVCxqNAetXjyUD4VoSuYh+sN+ZnSuGXPp45xx+8SJGEAChZrF8la6qHq6DGAnbGO5oDy7ropKA5aV3HC7mkefHFamLJl2rvhR68ERd8A3qiVk6gKGpk9jGqlFk/mBRmu8gJxxg2/Cig06AkvAo8IjjUNkVpDi0HpCA/EQBg2ACreX+cUG7CCpCpFnH2RfSy++GAl9Bd2iHRIcigqWEG4EISkwKh4WflRkEHZ4QxC9q/f8ZXgOXLDnZIiVJdEXP8q15SZYP9/pyyXQuPj9vKKaiFrDimxWp2SWOFCw8YcXf2BStvIIAvBHcvxd+OMAoiS1HFLkSqnqhYlg+cnFYJx1x4z/nsDKyO2yb0Z8V2JT59AfYjyjF+DOem4yo5YdtHwfKJR/lz4mufaDe/xzynO2c6RTqOHfJ31zIZuxFdrPYm5lg28ZNxNcaz/YWmXVLsK1halA3HdM1PJKUT1FTRh+VEmmTxOE6GkiuW+dGHdEAasmZ2wVtweRx6buGCew2Usgt5wEyTzQRVUfG7ZibcDncK+PuLU2BkoReh1FhhhNgclRR13k6MzeU+yg7qHrbxoYT29OTskbgGJYb7+xgV75Gyo5+DqyeezI8=
  space: qa
notifications:
  email:
    on_failure: change
    on_success: change
